import { Container } from "@/components/container";
import { Heading } from "@/components/heading";
import { Subheading } from "@/components/subheading";

export const metadata = {
  title: "Disclaimer — earlyroom",
  description: "Disclaimer for earlyroom by Albor Digital LLC.",
};

export default function DisclaimerPage() {
  return (
    <Container className="py-20 md:py-32">
      <div className="mx-auto max-w-3xl">
        <Heading as="h1">Disclaimer</Heading>
        <Subheading className="mt-4">
          Albor Digital LLC · Effective Date: January 1, 2026
        </Subheading>

        <div className="mt-12 flex flex-col gap-10">

          <LegalSection title="1. General Disclaimer">
            The products, tools, data, and content provided by Albor Digital LLC are offered for informational and practical utility purposes only. While we strive for accuracy and usefulness, we make no representations or warranties — express or implied — regarding the completeness, accuracy, reliability, or suitability of any information or tool for any particular purpose. All use is at your own risk.
          </LegalSection>

          <LegalSection title="2. No Professional Advice">
            Nothing provided through our products constitutes legal, financial, medical, investment, tax, or professional advice of any kind. Any data, analysis, or output generated by our tools — including AI-powered features — should not be relied upon as a substitute for advice from a qualified professional. Always seek independent professional guidance before making decisions based on our products.
          </LegalSection>

          <LegalSection title="3. AI-Generated Content">
            Where our products incorporate artificial intelligence, outputs are generated algorithmically and may contain errors, omissions, or inaccuracies. AI outputs reflect patterns in training data and do not represent verified facts, professional opinions, or the views of Albor Digital LLC. Users are solely responsible for evaluating and verifying any AI-generated content before acting on it.
          </LegalSection>

          <LegalSection title="4. Data and Market Information">
            Any market data, pricing information, or comparative statistics provided by our tools are compiled from publicly available sources and are intended for general reference only. Data may be incomplete, delayed, or subject to errors. Albor Digital LLC does not guarantee the accuracy of third-party data sources and is not responsible for decisions made based on such data.
          </LegalSection>

          <LegalSection title="5. External Links">
            Our products may reference or link to external websites and resources. Albor Digital LLC does not control and is not responsible for the content, accuracy, or availability of external sites. Inclusion of a link does not imply endorsement.
          </LegalSection>

          <LegalSection title="6. Limitation of Liability">
            To the fullest extent permitted by law, Albor Digital LLC and its owner shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from reliance on or use of our products, tools, data, or content — including any errors, interruptions, or inaccuracies therein.
          </LegalSection>

          <LegalSection title="7. Jurisdictional Notice">
            Our products are operated from Canada and the United States. We make no representation that our products are appropriate or available for use in all jurisdictions. Users who access our products from outside these regions do so at their own initiative and are responsible for compliance with local laws.
          </LegalSection>

        </div>
      </div>
    </Container>
  );
}

function LegalSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-3">
      <h2 className="text-base font-semibold text-neutral-900 dark:text-white">{title}</h2>
      <p className="text-sm leading-relaxed text-neutral-600 dark:text-neutral-400">{children}</p>
    </div>
  );
}
